// Single source of truth for module seed data
export const MODULE_SEED_DATA = [
  {
    slug: "welcome",
    title: "Welcome & Introduction",
    description: "Introduce the onboarding process and learn the customer's name.",
    displayOrder: 1,
    systemPromptFragment: `First question: "What's your business called?" — just that, nothing else. Put "This usually takes about 30 min. You can pause and come back anytime!" in sideTip. After they answer, say "Great name!" and ask the next question: "What type of business is it?" with buttons for common types (Yoga Studio, Fitness Gym, Spa/Salon, Pilates Studio, Dance Studio, Other). Mark "Other" as not recommended, mark the most common as recommended.`,
    content: {},
  },
  {
    slug: "onboarding-team",
    title: "Meet Your Onboarding Team",
    description: "Set communication preferences.",
    displayOrder: 2,
    systemPromptFragment: `Tell the customer they have a dedicated onboarding specialist. Ask ONE question: "How do you prefer to be contacted?" with buttons: Email (recommended), Phone, Text. Put the specialist info in sideTip.`,
    content: {},
  },
  {
    slug: "website-crawl",
    title: "Website Crawl",
    description: "Crawl the customer's website to pre-fill data.",
    displayOrder: 3,
    dependencyGroup: "data-collection",
    dependencyOrder: 1,
    systemPromptFragment: `Ask ONE question: "Do you have a website for your business?" with buttons: "Yes" (recommended), "Not yet". If yes, ask for the URL in the next turn. If no, skip to next module. Put "We can pull your business info, classes, and staff from your site to save you time!" in sideTip.`,
    content: {},
  },
  {
    slug: "business-basics",
    title: "Business Basics",
    description: "Collect business name, type, location.",
    displayOrder: 4,
    dependencyGroup: "data-collection",
    dependencyOrder: 2,
    systemPromptFragment: `Collect business basics ONE question at a time in this order: 1) Business address/location (text answer), 2) Is this a new or existing business? (buttons: "New business", "Existing business" recommended). If data was pre-filled from crawl, show it and ask "Does this look right?" with Yes/Edit buttons.`,
    content: {},
  },
  {
    slug: "payment-setup",
    title: "Payment Setup",
    description: "Guide payment processing setup.",
    displayOrder: 5,
    systemPromptFragment: `Ask: "Ready to set up payments?" with buttons: "Let's do it" (recommended), "Skip for now". If yes, show a checklist of what they'll need, then ask about each item ONE at a time. Put "This is the most important step — but don't worry, you can update it later!" in sideTip.`,
    content: { checklist: ["Business info (name, EIN/tax ID)", "Owner info (name, DOB)", "Government-issued ID", "Website URL", "Bank account details"] },
  },
  {
    slug: "class-collection",
    title: "Class Collection",
    description: "Gather class/service offerings.",
    displayOrder: 6,
    dependencyGroup: "services",
    dependencyOrder: 1,
    systemPromptFragment: `Ask: "Do you offer group classes?" with buttons: "Yes" (recommended), "No", "Skip for now". If yes, ask: "How would you like to add them?" with option_cards: "Type them in" (recommended), "Upload a spreadsheet". Then collect class names one by one, or accept a file upload. Put category suggestions in sideTip, not in chat.`,
    content: { suggestedCategories: ["Yoga", "Pilates", "HIIT", "Cycling", "Barre", "Strength", "Cardio", "Dance", "Martial Arts", "Swimming", "Meditation", "Other"] },
  },
  {
    slug: "appointment-collection",
    title: "Appointment Collection",
    description: "Collect appointment/service types.",
    displayOrder: 7,
    dependencyGroup: "services",
    dependencyOrder: 2,
    systemPromptFragment: `Ask: "Do you offer one-on-one appointments or private sessions?" with buttons: "Yes" (recommended), "No", "Skip for now". If yes, ask for service names one at a time. Keep it simple.`,
    content: {},
  },
  {
    slug: "staff-details",
    title: "Staff Details",
    description: "Collect staff/instructor information.",
    displayOrder: 8,
    systemPromptFragment: `Ask: "How many staff members or instructors do you have?" with quick_reply options: "Just me", "2-5", "6-10", "10+". Then ask: "How would you like to add them?" with buttons: "Type them in" (recommended), "Upload a spreadsheet". Collect names one at a time if typing.`,
    content: {},
  },
  {
    slug: "pricing-options",
    title: "Pricing Options",
    description: "Define pricing tiers and packages.",
    displayOrder: 9,
    dependencyGroup: "pricing",
    dependencyOrder: 1,
    systemPromptFragment: `Ask: "How do you charge for your services?" with option_cards: "Drop-in rates" (recommended), "Class packs", "Monthly memberships", "Mix of these". Then collect pricing details one question at a time based on their answer.`,
    content: {},
  },
  {
    slug: "memberships-contracts",
    title: "Memberships & Contracts",
    description: "Set up membership types and terms.",
    displayOrder: 10,
    dependencyGroup: "pricing",
    dependencyOrder: 2,
    systemPromptFragment: `Ask: "Do you offer memberships or recurring contracts?" with buttons: "Yes" (recommended), "No", "Skip for now". If yes, ask for membership name first, then price, then billing frequency — one at a time.`,
    content: {},
  },
  {
    slug: "branding-logo",
    title: "Branding & Logo",
    description: "Upload logo and set brand colors.",
    displayOrder: 11,
    systemPromptFragment: `Ask: "Do you have a logo to upload?" with buttons: "Yes, upload now" (recommended), "I'll add it later". If yes, show a file_dropzone for image upload. Then ask about brand colors with quick_reply: common color options. Keep it fun — put "This is where your personality shines!" in sideTip.`,
    content: {},
  },
  {
    slug: "marketplace",
    title: "Mindbody Marketplace",
    description: "Explain the Marketplace and help get listed.",
    displayOrder: 12,
    systemPromptFragment: `Ask: "Want to be listed on the Mindbody Marketplace so new clients can find you?" with buttons: "Yes please!" (recommended), "Tell me more", "Skip for now". Put marketplace benefits in sideTip, not in chat. Keep the chat message to one sentence.`,
    content: {},
  },
  {
    slug: "classpass",
    title: "ClassPass Integration",
    description: "Explain ClassPass integration.",
    displayOrder: 13,
    systemPromptFragment: `Ask: "Interested in getting clients through ClassPass?" with buttons: "Yes" (recommended), "What's ClassPass?", "No thanks". Put ClassPass explanation in sideTip. Keep chat to one sentence.`,
    content: {},
  },
  {
    slug: "kickoff-call",
    title: "Kickoff Call Booking",
    description: "Schedule a kickoff call with the onboarding team.",
    displayOrder: 14,
    systemPromptFragment: `Congratulate them briefly (one sentence). Ask: "Ready to book your kickoff call with our team?" with buttons: "Book now" (recommended), "I'll book later". Put a summary of what they accomplished in sideTip.`,
    content: {},
  },
];
